# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: normanrotabull
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: customersupport
# "service" is the name of this project. This will also be added to your AWS resource names.
service: customersupport

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 900
  #Timeout needs to be 15 minutes to allow for data fetching to complete

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"
  scheduled:
    handler: src/scheduledJobHandler.handler
    events:
      - schedule: cron(0 0 ? * SUN *)
plugins:
  - serverless-dotenv-plugin

package:
  patterns:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"
    - "!node_modules/.cache/prisma/**" # only required for Windows
